/**
 * Tailwind & DaisyUI Configuration
 *
 * Uses 6 wellness themes from the wellness UI brief.
 * Footer uses custom fixed colors to remain always dark.
 */

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Commissioner', 'system-ui', 'sans-serif'],
      },
      colors: {
        // Footer uses fixed colors - always dark regardless of theme
        'footer-bg': '#2C3532',      // Dark grey-green for footer
        'footer-text': '#E7ECEA',    // Light text for footer
        // Semantic text colors - provide proper contrast in both themes
        'text-secondary': 'var(--color-text-secondary)',  // For metadata, times, locations
        'text-muted': 'var(--color-text-muted)',          // For tags, less important info
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      'light',  // Original DaisyUI light theme
      'dark',   // Original DaisyUI dark theme
      {
        "zen-garden": {
          "color-scheme": "light",
          "primary": "#9CAF88",
          "primary-content": "#1a1f16",
          "secondary": "#C3B1E1",
          "secondary-content": "#2d2639",
          "accent": "#D4A574",
          "accent-content": "#2d2317",
          "neutral": "#6B6B6B",
          "neutral-content": "#f5f5f5",
          "base-100": "#FAF8F5",
          "base-200": "#F0EDE8",
          "base-300": "#E5E0D8",
          "base-content": "#3D3D3D",
          "info": "#7EB8B6",
          "info-content": "#0f2524",
          "success": "#86EFAC",
          "success-content": "#14532D",
          "warning": "#FDE68A",
          "warning-content": "#78350F",
          "error": "#FCA5A5",
          "error-content": "#7F1D1D",
          "--rounded-btn": "0.5rem",
          "--rounded-box": "0.75rem",
        },
      },
      {
        "zen-garden-dark": {
          "color-scheme": "dark",
          "primary": "#7A8F6A",
          "primary-content": "#F0EDE8",
          "secondary": "#9A8BB8",
          "secondary-content": "#E8E0F0",
          "accent": "#C49464",
          "accent-content": "#FAF8F5",
          "neutral": "#4A4A4A",
          "neutral-content": "#E5E5E5",
          "base-100": "#1E1E1C",
          "base-200": "#2A2A26",
          "base-300": "#3A3A34",
          "base-content": "#F5F3F0",
          "info": "#5A9896",
          "info-content": "#E0F2F1",
          "success": "#4ADE80",
          "success-content": "#14532D",
          "warning": "#FACC15",
          "warning-content": "#78350F",
          "error": "#F87171",
          "error-content": "#FEE2E2",
          "--rounded-btn": "0.5rem",
          "--rounded-box": "0.75rem",
        },
      },
      {
        "serene-ocean": {
          "color-scheme": "light",
          "primary": "#7EB8B6",
          "primary-content": "#0f2524",
          "secondary": "#A8C4D9",
          "secondary-content": "#1e2d38",
          "accent": "#D4C5A9",
          "accent-content": "#2d2a1f",
          "neutral": "#64748B",
          "neutral-content": "#f1f5f9",
          "base-100": "#F9FAFB",
          "base-200": "#F1F5F9",
          "base-300": "#E2E8F0",
          "base-content": "#334155",
          "info": "#7EB8B6",
          "info-content": "#0f2524",
          "success": "#86EFAC",
          "success-content": "#14532D",
          "warning": "#FDE68A",
          "warning-content": "#78350F",
          "error": "#FCA5A5",
          "error-content": "#7F1D1D",
          "--rounded-btn": "0.75rem",
          "--rounded-box": "1rem",
        },
      },
      {
        "serene-ocean-dark": {
          "color-scheme": "dark",
          "primary": "#5A9896",
          "primary-content": "#E0F2F1",
          "secondary": "#7A9BB8",
          "secondary-content": "#E3EDF5",
          "accent": "#B8A888",
          "accent-content": "#FAF8F5",
          "neutral": "#475569",
          "neutral-content": "#E2E8F0",
          "base-100": "#0F1419",
          "base-200": "#1A2330",
          "base-300": "#293548",
          "base-content": "#F1F5F9",
          "info": "#5A9896",
          "info-content": "#E0F2F1",
          "success": "#4ADE80",
          "success-content": "#14532D",
          "warning": "#FACC15",
          "warning-content": "#78350F",
          "error": "#F87171",
          "error-content": "#FEE2E2",
          "--rounded-btn": "0.75rem",
          "--rounded-box": "1rem",
        },
      },
      {
        "tranquil-dawn": {
          "color-scheme": "light",
          "primary": "#D4A5A5",
          "primary-content": "#2d1f1f",
          "secondary": "#B8A9C9",
          "secondary-content": "#2a2533",
          "accent": "#C9B97A",
          "accent-content": "#2d2a17",
          "neutral": "#8B7E8E",
          "neutral-content": "#faf8fb",
          "base-100": "#FDF9F7",
          "base-200": "#F8F2EF",
          "base-300": "#EFE6E2",
          "base-content": "#4A3F55",
          "info": "#A8C4D9",
          "info-content": "#1e2d38",
          "success": "#86EFAC",
          "success-content": "#14532D",
          "warning": "#FDE68A",
          "warning-content": "#78350F",
          "error": "#FCA5A5",
          "error-content": "#7F1D1D",
          "--rounded-btn": "1rem",
          "--rounded-box": "1rem",
        },
      },
      {
        "tranquil-dawn-dark": {
          "color-scheme": "dark",
          "primary": "#B88585",
          "primary-content": "#FDF5F5",
          "secondary": "#9889A8",
          "secondary-content": "#F0EBF5",
          "accent": "#A89A5A",
          "accent-content": "#FDF9F7",
          "neutral": "#5A4D5E",
          "neutral-content": "#E8E0EA",
          "base-100": "#1A1618",
          "base-200": "#2A2428",
          "base-300": "#3D343A",
          "base-content": "#F8F5F5",
          "info": "#7A9BB8",
          "info-content": "#E3EDF5",
          "success": "#4ADE80",
          "success-content": "#14532D",
          "warning": "#FACC15",
          "warning-content": "#78350F",
          "error": "#F87171",
          "error-content": "#FEE2E2",
          "--rounded-btn": "1rem",
          "--rounded-box": "1rem",
        },
      },
    ],
  },
}
